# A workflow to generate and update GitHub metrics automatically
name: GitHub Metrics

# This workflow is triggered on a schedule (daily at 00:00 UTC) and on manual trigger
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  # The job that generates the metrics
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout the repository to access the files
      - uses: actions/checkout@v4

      # Run the metrics action
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Replace with your GitHub username
          user: JhonatanMotaDev
          # The GitHub token with permissions to read user data
          token: ${{ secrets.METRICS_TOKEN }}
          # The name of the output file
          output_path: github-metrics.svg
